// src/components/packages/EmptyPackage.vue
<template>
  <div class="min-h-[600px] bg-white/5 rounded-lg p-6">
    <input
      v-model="packageName"
      @change="handleNameChange"
      placeholder="Enter package name"
      class="text-3xl font-bold text-white mb-4 bg-white/10 border-white/20 rounded px-2 py-1 w-full"
    />
    <div class="flex flex-col items-center justify-center h-[calc(100%-4rem)]">
      <p class="text-white/50">This package is empty</p>
      <p class="text-white/30 text-sm">Add items to get started</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const emit = defineEmits<{
  (e: 'nameChange', value: string): void;
}>();

const packageName = ref('');

const handleNameChange = () => {
  if (packageName.value.trim()) {
    emit('nameChange', packageName.value);
  }
};
</script>

// src/components/packages/EmptyPackage.tsx
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useState } from "react";
import { Package } from "@/types/package";
import PaymentSummary from "./PaymentSummary";
import { MoveHorizontal } from "lucide-react";

interface EmptyPackageProps {
  onNameChange: (name: string) => void;
}

const EmptyPackage = ({ onNameChange }: EmptyPackageProps) => {
  const [packageName, setPackageName] = useState("New Package");

  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setPackageName(e.target.value);
    onNameChange(e.target.value);
  };

  return (
    <div className="space-y-4 w-[400px] bg-white/5 backdrop-blur-sm p-6 rounded-lg">
      <Input
        value={packageName}
        onChange={handleNameChange}
        className="font-bold text-lg"
        placeholder="Package Name"
      />
      <Card className="h-[400px] flex items-center justify-center bg-sidebar-accent/5">
        <CardContent className="text-center text-muted-foreground flex flex-col items-center gap-4">
          <MoveHorizontal className="h-12 w-12 text-muted-foreground/50" />
          <div>
            <p className="text-lg font-medium mb-2">This package is empty</p>
            <p className="text-sm">Drag items from other packages or add-ons</p>
            <p className="text-sm text-muted-foreground/70">to start building your package</p>
          </div>
        </CardContent>
      </Card>
      <PaymentSummary packages={[]} title="Custom" />
    </div>
  );
};

export default EmptyPackage;
