// src/components/packages/EmptyPackage.tsx
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { useState } from "react";
import { Package } from "@/types/package";
import PaymentSummary from "./PaymentSummary";
import { MoveHorizontal } from "lucide-react";

interface EmptyPackageProps {
  onNameChange: (name: string) => void;
}

const EmptyPackage = ({ onNameChange }: EmptyPackageProps) => {
  const [packageName, setPackageName] = useState("New Package");

  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setPackageName(e.target.value);
    onNameChange(e.target.value);
  };

  return (
    <div className="space-y-4 w-[400px] bg-white/5 backdrop-blur-sm p-6 rounded-lg">
      <Input
        value={packageName}
        onChange={handleNameChange}
        className="font-bold text-lg"
        placeholder="Package Name"
      />
      <Card className="h-[400px] flex items-center justify-center bg-sidebar-accent/5">
        <CardContent className="text-center text-muted-foreground flex flex-col items-center gap-4">
          <MoveHorizontal className="h-12 w-12 text-muted-foreground/50" />
          <div>
            <p className="text-lg font-medium mb-2">This package is empty</p>
            <p className="text-sm">Drag items from other packages or add-ons</p>
            <p className="text-sm text-muted-foreground/70">to start building your package</p>
          </div>
        </CardContent>
      </Card>
      <PaymentSummary packages={[]} title="Custom" />
    </div>
  );
};

export default EmptyPackage;

// src/components/EmptyPackage.vue
<template>
  <div class="empty-package">
    <input
      v-model="packageName"
      @input="handleNameChange"
      class="package-name-input"
      placeholder="Package Name"
    />
    
    <div class="empty-card">
      <div class="empty-content">
        <span class="move-icon">↔</span>
        <div class="empty-text">
          <p class="empty-title">This package is empty</p>
          <p class="empty-subtitle">Drag items from other packages or add-ons</p>
          <p class="empty-description">to start building your package</p>
        </div>
      </div>
    </div>
    
    <payment-summary 
      :packages="[]" 
      title="Custom"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import PaymentSummary from './PaymentSummary.vue';

interface Props {
  onNameChange: (name: string) => void;
}

const props = defineProps<Props>();
const packageName = ref('New Package');

const handleNameChange = () => {
  props.onNameChange(packageName.value);
};
</script>

<style scoped>
.empty-package {
  width: 400px;
  padding: 1.5rem;
  background-color: rgba(255, 255, 255, 0.05);
  backdrop-filter: blur(8px);
  border-radius: 0.5rem;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.package-name-input {
  padding: 0.5rem;
  font-size: 1.125rem;
  font-weight: bold;
  background-color: transparent;
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 0.375rem;
  color: white;
  width: 100%;
}

.empty-card {
  height: 400px;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgba(255, 255, 255, 0.05);
  border-radius: 0.5rem;
}

.empty-content {
  text-align: center;
  color: rgba(255, 255, 255, 0.5);
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1rem;
}

.move-icon {
  font-size: 3rem;
  opacity: 0.5;
}

.empty-text {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.empty-title {
  font-size: 1.125rem;
  font-weight: 500;
  color: rgba(255, 255, 255, 0.8);
}

.empty-subtitle {
  font-size: 0.875rem;
  color: rgba(255, 255, 255, 0.6);
}

.empty-description {
  font-size: 0.875rem;
  color: rgba(255, 255, 255, 0.4);
}
</style>
