// src/components/packages/PackageControls.tsx
import { Button } from "@/components/ui/button";
import { ChevronLeft, ChevronRight, Plus, Trash2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface PackageControlsProps {
  onPrevious: () => void;
  onNext: () => void;
  onAdd: () => void;
  onDelete: () => void;
  canGoPrevious: boolean;
  canGoNext: boolean;
  showDelete: boolean;
}

const PackageControls = ({
  onPrevious,
  onNext,
  onAdd,
  onDelete,
  canGoPrevious,
  canGoNext,
  showDelete
}: PackageControlsProps) => {
  return (
    <div className="flex flex-col gap-4 self-center">
      <Button
        variant="ghost"
        size="icon"
        onClick={onPrevious}
        disabled={!canGoPrevious}
        className="text-white hover:bg-white/20 h-12 w-12"
      >
        <ChevronLeft className="h-6 w-6" />
      </Button>
      <Button
        variant="ghost"
        size="icon"
        onClick={onNext}
        disabled={!canGoNext}
        className="text-white hover:bg-white/20 h-12 w-12"
      >
        <ChevronRight className="h-6 w-6" />
      </Button>
      <Button
        variant="ghost"
        size="icon"
        onClick={onAdd}
        className="text-white hover:bg-white/20 h-12 w-12"
      >
        <Plus className="h-6 w-6" />
      </Button>
      {showDelete && (
        <Button
          variant="ghost"
          size="icon"
          onClick={onDelete}
          className="text-white hover:bg-white/20 h-12 w-12"
        >
          <Trash2 className="h-6 w-6" />
        </Button>
      )}
    </div>
  );
};

export default PackageControls;

// src/components/PackageControls.vue
<template>
  <div class="package-controls">
    <button 
      @click="onPrevious" 
      :disabled="!canGoPrevious"
      class="control-button"
    >
      <span class="icon">←</span>
    </button>
    
    <button 
      @click="onNext" 
      :disabled="!canGoNext"
      class="control-button"
    >
      <span class="icon">→</span>
    </button>
    
    <button 
      @click="onAdd"
      class="control-button"
    >
      <span class="icon">+</span>
    </button>
    
    <button 
      v-if="showDelete"
      @click="onDelete"
      class="control-button delete"
    >
      <span class="icon">×</span>
    </button>
  </div>
</template>

<script setup lang="ts">
interface Props {
  onPrevious: () => void;
  onNext: () => void;
  onAdd: () => void;
  onDelete: () => void;
  canGoPrevious: boolean;
  canGoNext: boolean;
  showDelete: boolean;
}

defineProps<Props>();
</script>

<style scoped>
.package-controls {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  align-self: center;
}

.control-button {
  width: 3rem;
  height: 3rem;
  border: none;
  border-radius: 50%;
  background-color: rgba(255, 255, 255, 0.1);
  color: white;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background-color 0.2s;
}

.control-button:hover:not(:disabled) {
  background-color: rgba(255, 255, 255, 0.2);
}

.control-button:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.control-button.delete:hover {
  background-color: rgba(239, 68, 68, 0.2);
}

.icon {
  font-size: 1.5rem;
  line-height: 1;
}
</style>
